# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.0 # executor for the build job

    working_directory: ~/project

    steps:
      - checkout # checkout source code to working directory

      # Download and cache dependencies using checksum on requirements.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            make setup
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # use persist to workspace to persist between jobs in one workflow
      - persist_to_workspace:
          root: ~/
          paths:
            - "project"
      - run:
          name: lint code
          command: |
            . venv/bin/activate
            make lint
      - run:
          name: test code
          command: |
            . venv/bin/activate
            make test

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
