# This is a basic workflow to help you get started with Actions

name: Build Infra in GCP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths:
      - iac/**
  pull_request:
    branches: [main]
    paths:
      - iac/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# this only allows one job to run for each env at a time
concurrency:
  group: environment-${{ github.ref }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_dev:
    name: Deploy Dev IaC
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GCLOUD_KEY_DEV }}
      BUILD_ENV: dev
      TERRAFORM_DIR: iac/dev
    # set working directory for all of the job commands to be executed from
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_DIR }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform 🧱
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0-alpha20210616
          terraform_wrapper: false
        
      - name: Terraform Init
        run: |
          terraform init
      - name: Terraform Plan
        run: |
          terraform plan
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
      - name: Terraform Output
        run: |
          terraform output
  deploy_prod:
    name: Deploy Prod IaC
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GCLOUD_KEY_PROD }}
      BUILD_ENV: prod
      TERRAFORM_DIR: iac/prod
    # set working directory for all of the job commands to be executed from
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_DIR }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform 🧱
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0-alpha20210616
          terraform_wrapper: false
        
      - name: Terraform Init
        run: |
          terraform init
      - name: Terraform Plan
        run: |
          terraform plan
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
      - name: Terraform Output
        run: |
          terraform output
