# This is a basic workflow to help you get started with Actions

name: Deploy Web App to GAE - DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [GP-36_big-query-cron]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# this only allows one job to run for each env at a time
concurrency:
  group: environment-${{ github.ref }}

env:
  BUILD_ENV: dev
  WEB_APP_DIR: ./gae_web_service

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint_test:
    name: Lint and Test Application Code
    runs-on: ubuntu-latest
    # set working directory for all of the job commands to be executed from
    defaults:
      run:
        working-directory: ${{ env.WEB_APP_DIR }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: actions/checkout@v2
      - name: Setup
        run: make setup
      - name: Install Dev dependencies
        run: make install_dev
      - name: Lint Code
        run: make lint
      - name: Test Code
        run: make test
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    needs: lint_test

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          # project_id: ${{ steps.tf_output.outputs.gcp_project_id }} # optional, to override the project set by config from key. 
          credentials: ${{ secrets.GCLOUD_KEY_DEV }}
